{
 "title": "Consumer dashboard",
 "time": { "from": "2026-01-04T15:53:25.957Z", "to": "2026-01-04T15:56:39.409Z" },
 "panels": [
  {
   "title": "RPS по этапам",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(consumer_stage_messages_total[20s])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "RPS максимум",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(consumer_stage_messages_total{stage=\"processed\"}[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag консумера",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(consumer_lag_seconds_bucket[5s]))",
     "legendFormat": "P99 (max)"
    },
    {
     "expr": "rate(consumer_lag_seconds_sum[5s]) / rate(consumer_lag_seconds_count[5s])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Время ответа API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(consumer_api_response_duration_seconds_bucket[15s]))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(consumer_api_response_duration_seconds_bucket[15s]))",
     "legendFormat": "P99"
    },
    {
     "expr": "rate(consumer_api_response_duration_seconds_sum[15s]) / rate(consumer_api_response_duration_seconds_count[15s])",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}