{
 "title": "Join Dashboard",
 "time": { "from": "2026-01-14T13:25:05.691Z", "to": "2026-01-14T13:27:08.992Z" },
 "panels": [
  {
   "title": "RPS всей системы",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(producer_messages_sent_total[5s])",
     "legendFormat": "Продюсер"
    },
    {
     "expr": "rate(consumer_stage_messages_total{stage=\"processed\"}[5s])",
     "legendFormat": "Консумер"
    },
    {
     "expr": "rate(service_messages_processed_total[5s])\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Задержки системы",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(consumer_api_response_time_bucket[5s]))",
     "legendFormat": "API 95%"
    },
    {
     "expr": "histogram_quantile(0.95, rate(service_db_operation_duration_seconds_bucket[5s]))",
     "legendFormat": "{{instance}} - БД 95%"
    },
    {
     "expr": "avg(rate(consumer_lag_seconds_sum[15s])) / avg(rate(consumer_lag_seconds_count[15s]))",
     "legendFormat": "Lag кафки"
    }
   ]
  },
  {
   "title": "Всего обработано",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "сообщений" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(producer_messages_sent_total)",
     "legendFormat": "Создано"
    },
    {
     "expr": "sum(service_messages_processed_total)",
     "legendFormat": "Сохранено"
    }
   ]
  }
 ]
}