{
 "title": "Producer Dashboard",
 "time": { "from": "2025-12-25T15:54:15.082Z", "to": "2025-12-25T16:02:35.530Z" },
 "panels": [
  {
   "title": "RPS продюсера",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(producer_messages_sent_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS генерации",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(producer_messages_generated_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки/сек",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(producer_messages_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время генерации (P95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(producer_generate_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}