{
 "title": "Service Dashboard",
 "time": { "from": "2026-01-14T16:17:36.963Z", "to": "2026-01-14T16:18:04.669Z" },
 "panels": [
  {
   "title": "RPS сервиса",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(service_messages_processed_total[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Время ответа сервиса",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, rate(service_db_operation_duration_seconds_bucket[30s])))",
     "legendFormat": "95% батчей"
    },
    {
     "expr": "avg(histogram_quantile(0.50, rate(service_db_operation_duration_seconds_bucket[30s])))",
     "legendFormat": "50% (медиана)"
    }
   ]
  },
  {
   "title": "Инстансы сервиса",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "сообщений" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_messages_processed_total",
     "legendFormat": "{{instance}} - {{value}}"
    }
   ]
  }
 ]
}