// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/grep.proto

package grep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Задача, отправляемая воркеру
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`                                      // строки для обработки
	StartLineNum  int32                  `protobuf:"varint,2,opt,name=start_line_num,json=startLineNum,proto3" json:"start_line_num,omitempty"` // глобальный номер первой строки
	After         int32                  `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`                                     // -A
	Before        int32                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`                                   // -B
	Context       int32                  `protobuf:"varint,5,opt,name=context,proto3" json:"context,omitempty"`                                 // -C
	Count         bool                   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`                                     // -c
	IgnoreCase    bool                   `protobuf:"varint,7,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`         // -i
	Invert        bool                   `protobuf:"varint,8,opt,name=invert,proto3" json:"invert,omitempty"`                                   // -v
	Fixed         bool                   `protobuf:"varint,9,opt,name=fixed,proto3" json:"fixed,omitempty"`                                     // -F
	LineNumber    bool                   `protobuf:"varint,10,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`        // -n
	Pattern       string                 `protobuf:"bytes,11,opt,name=pattern,proto3" json:"pattern,omitempty"`                                 // шаблон поиска
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_grep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_grep_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Task) GetStartLineNum() int32 {
	if x != nil {
		return x.StartLineNum
	}
	return 0
}

func (x *Task) GetAfter() int32 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *Task) GetBefore() int32 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *Task) GetContext() int32 {
	if x != nil {
		return x.Context
	}
	return 0
}

func (x *Task) GetCount() bool {
	if x != nil {
		return x.Count
	}
	return false
}

func (x *Task) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *Task) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *Task) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *Task) GetLineNumber() bool {
	if x != nil {
		return x.LineNumber
	}
	return false
}

func (x *Task) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

// Результат обработки
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`  // найденные строки (если не -c)
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // количество совпадений (если -c)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`  // текст ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_grep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_grep_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Result) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_grep_proto protoreflect.FileDescriptor

const file_proto_grep_proto_rawDesc = "" +
	"\n" +
	"\x10proto/grep.proto\x12\x04grep\"\xaa\x02\n" +
	"\x04Task\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12$\n" +
	"\x0estart_line_num\x18\x02 \x01(\x05R\fstartLineNum\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x05R\x05after\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x05R\x06before\x12\x18\n" +
	"\acontext\x18\x05 \x01(\x05R\acontext\x12\x14\n" +
	"\x05count\x18\x06 \x01(\bR\x05count\x12\x1f\n" +
	"\vignore_case\x18\a \x01(\bR\n" +
	"ignoreCase\x12\x16\n" +
	"\x06invert\x18\b \x01(\bR\x06invert\x12\x14\n" +
	"\x05fixed\x18\t \x01(\bR\x05fixed\x12\x1f\n" +
	"\vline_number\x18\n" +
	" \x01(\bR\n" +
	"lineNumber\x12\x18\n" +
	"\apattern\x18\v \x01(\tR\apattern\"J\n" +
	"\x06Result\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error26\n" +
	"\vGrepService\x12'\n" +
	"\vProcessTask\x12\n" +
	".grep.Task\x1a\f.grep.ResultB5Z3github.com/IPampurin/DistributedMyGoGrep/proto;grepb\x06proto3"

var (
	file_proto_grep_proto_rawDescOnce sync.Once
	file_proto_grep_proto_rawDescData []byte
)

func file_proto_grep_proto_rawDescGZIP() []byte {
	file_proto_grep_proto_rawDescOnce.Do(func() {
		file_proto_grep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grep_proto_rawDesc), len(file_proto_grep_proto_rawDesc)))
	})
	return file_proto_grep_proto_rawDescData
}

var file_proto_grep_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grep_proto_goTypes = []any{
	(*Task)(nil),   // 0: grep.Task
	(*Result)(nil), // 1: grep.Result
}
var file_proto_grep_proto_depIdxs = []int32{
	0, // 0: grep.GrepService.ProcessTask:input_type -> grep.Task
	1, // 1: grep.GrepService.ProcessTask:output_type -> grep.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grep_proto_init() }
func file_proto_grep_proto_init() {
	if File_proto_grep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grep_proto_rawDesc), len(file_proto_grep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grep_proto_goTypes,
		DependencyIndexes: file_proto_grep_proto_depIdxs,
		MessageInfos:      file_proto_grep_proto_msgTypes,
	}.Build()
	File_proto_grep_proto = out.File
	file_proto_grep_proto_goTypes = nil
	file_proto_grep_proto_depIdxs = nil
}
