// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/grep.proto

package grep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrepService_ProcessTask_FullMethodName = "/grep.GrepService/ProcessTask"
)

// GrepServiceClient is the client API for GrepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис grep
type GrepServiceClient interface {
	ProcessTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Result, error)
}

type grepServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrepServiceClient(cc grpc.ClientConnInterface) GrepServiceClient {
	return &grepServiceClient{cc}
}

func (c *grepServiceClient) ProcessTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, GrepService_ProcessTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrepServiceServer is the server API for GrepService service.
// All implementations must embed UnimplementedGrepServiceServer
// for forward compatibility.
//
// Сервис grep
type GrepServiceServer interface {
	ProcessTask(context.Context, *Task) (*Result, error)
	mustEmbedUnimplementedGrepServiceServer()
}

// UnimplementedGrepServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrepServiceServer struct{}

func (UnimplementedGrepServiceServer) ProcessTask(context.Context, *Task) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTask not implemented")
}
func (UnimplementedGrepServiceServer) mustEmbedUnimplementedGrepServiceServer() {}
func (UnimplementedGrepServiceServer) testEmbeddedByValue()                     {}

// UnsafeGrepServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrepServiceServer will
// result in compilation errors.
type UnsafeGrepServiceServer interface {
	mustEmbedUnimplementedGrepServiceServer()
}

func RegisterGrepServiceServer(s grpc.ServiceRegistrar, srv GrepServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrepServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrepService_ServiceDesc, srv)
}

func _GrepService_ProcessTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepServiceServer).ProcessTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrepService_ProcessTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepServiceServer).ProcessTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

// GrepService_ServiceDesc is the grpc.ServiceDesc for GrepService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrepService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grep.GrepService",
	HandlerType: (*GrepServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTask",
			Handler:    _GrepService_ProcessTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grep.proto",
}
