services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - ${L0_PORT}:8081
    volumes:
      - .:/usr/src/app
    command: go run main.go
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DBL0_USER}
      - POSTGRES_PASSWORD=${DBL0_PASSWORD}
      - POSTGRES_DB=${DBL0_NAME}
    ports:
      - ${DBL0_PORT}:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    ports:
      - ${KAFKAL0_PORT}:9092
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_LOG_RETENTION_HOURS=168 # 1 неделя
      - KAFKA_LOG4J_LOGGING_LEVEL=INFO
    volumes:
      - kafka-data:/bitnami/kafka/data

volumes:
  postgres-db:
  kafka-data: